services:
  omniparser:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: omniparser
    ports:
      - "2171:2171"
    environment:
      - PYTHONPATH=/app/OmniParser
    volumes:
      - ./server:/app/server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    mem_limit: 8g
    memswap_limit: 12g
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2171/api/health"]
      interval: 30s
      timeout: 30s
      retries: 20
      start_period: 300s
